package Windows;

import Models.User;
import Services.UsersService;
import Utilities.WindowsBackground.CustomPanel;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.sun.awt.AWTUtilities;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.apache.commons.codec.digest.DigestUtils;

/**
 * @author JD101
 *
 * Interfaz grafica de la ventana de inicio de sesión.
 */
public class Login extends javax.swing.JFrame {

    //  Variables and Objects
    //  ------------------------------------------------------------------------
    private int x;
    private int y;
    //  ------------------------------------------------------------------------

    /**
     * Creates new form Login
     */
    public Login() {

        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Images/Logo/logo.png")).getImage());
        AWTUtilities.setWindowOpaque(this, false);
        setLocationRelativeTo(null);
        this.getRootPane().setDefaultButton(buttonLogin);

    }

    /**
     * Crea un nuevo formulario Login.
     *
     * @param window Recibe un parámetro tipo JFrame para localizarse de acuerdo
     * a este.
     */
    public Login(JFrame window) {

        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Images/Logo/logo.png")).getImage());
        AWTUtilities.setWindowOpaque(this, false);
        setLocationRelativeTo(window);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackgroundBelow = new CustomPanel("/Images/Login/backgroundBelow.png");
        panelBackgroundAbove = new CustomPanel("/Images/Login/background.png");
        buttonLogin = new javax.swing.JButton();
        passwordFieldPassword = new javax.swing.JPasswordField();
        labelPassword = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        textFieldUser = new javax.swing.JTextField();
        labelGreeting = new javax.swing.JLabel();
        labelUserIcon = new javax.swing.JLabel();
        buttonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar sesión");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(450, 555));
        setResizable(false);

        panelBackgroundBelow.setPreferredSize(new java.awt.Dimension(450, 550));
        panelBackgroundBelow.setRequestFocusEnabled(false);
        panelBackgroundBelow.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelBackgroundBelowMouseDragged(evt);
            }
        });
        panelBackgroundBelow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBackgroundBelowMousePressed(evt);
            }
        });

        panelBackgroundAbove.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelBackgroundAbove.setPreferredSize(new java.awt.Dimension(350, 450));

        buttonLogin.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/buttonLogin.png"))); // NOI18N
        buttonLogin.setText("Ingresar");
        buttonLogin.setBorder(null);
        buttonLogin.setBorderPainted(false);
        buttonLogin.setFocusPainted(false);
        buttonLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonLogin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/buttonLoginRollOver.png"))); // NOI18N
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        passwordFieldPassword.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        passwordFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldPasswordActionPerformed(evt);
            }
        });

        labelPassword.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        labelPassword.setText("Contraseña:");

        labelUser.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        labelUser.setText("Usuario:");

        textFieldUser.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        textFieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldUserActionPerformed(evt);
            }
        });

        labelGreeting.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        labelGreeting.setText("Bienvenido");

        labelUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/userIcon.png"))); // NOI18N

        buttonExit.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        buttonExit.setForeground(new java.awt.Color(255, 255, 255));
        buttonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/buttonLogin.png"))); // NOI18N
        buttonExit.setText("Salir");
        buttonExit.setBorder(null);
        buttonExit.setBorderPainted(false);
        buttonExit.setFocusPainted(false);
        buttonExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/buttonLoginRollOver.png"))); // NOI18N
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBackgroundAboveLayout = new javax.swing.GroupLayout(panelBackgroundAbove);
        panelBackgroundAbove.setLayout(panelBackgroundAboveLayout);
        panelBackgroundAboveLayout.setHorizontalGroup(
            panelBackgroundAboveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundAboveLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(panelBackgroundAboveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBackgroundAboveLayout.createSequentialGroup()
                        .addComponent(labelUser)
                        .addGap(38, 38, 38)
                        .addComponent(textFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBackgroundAboveLayout.createSequentialGroup()
                        .addComponent(labelPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passwordFieldPassword)))
                .addGap(27, 27, 27))
            .addGroup(panelBackgroundAboveLayout.createSequentialGroup()
                .addGroup(panelBackgroundAboveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundAboveLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(buttonLogin)
                        .addGap(50, 50, 50)
                        .addComponent(buttonExit))
                    .addGroup(panelBackgroundAboveLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(labelUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelBackgroundAboveLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(labelGreeting)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBackgroundAboveLayout.setVerticalGroup(
            panelBackgroundAboveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundAboveLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(labelUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(labelGreeting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(panelBackgroundAboveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUser)
                    .addComponent(textFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBackgroundAboveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(panelBackgroundAboveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLogin)
                    .addComponent(buttonExit))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBackgroundBelowLayout = new javax.swing.GroupLayout(panelBackgroundBelow);
        panelBackgroundBelow.setLayout(panelBackgroundBelowLayout);
        panelBackgroundBelowLayout.setHorizontalGroup(
            panelBackgroundBelowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundBelowLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(panelBackgroundAbove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panelBackgroundBelowLayout.setVerticalGroup(
            panelBackgroundBelowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundBelowLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(panelBackgroundAbove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackgroundBelow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackgroundBelow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //  Own Code
    //  ------------------------------------------------------------------------
    private void passwordFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldPasswordActionPerformed
        passwordFieldPassword.transferFocus();
    }//GEN-LAST:event_passwordFieldPasswordActionPerformed

    /**
     * Evalúa las credenciales ingresadas en el login para conceder acceso o no.
     *
     * @param evt
     */
    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed

        UsersService usersService = new UsersService();
        User user = new User();
        String password = new String(passwordFieldPassword.getPassword());
        boolean textFieldUserEmpty = !textFieldUser.getText().equals("");
        boolean passwordFieldPasswordEmpty = !password.equals("");

        if (textFieldUserEmpty && passwordFieldPasswordEmpty) {

            String encryptedPassword = DigestUtils.md5Hex(password);

            user.setUserName(textFieldUser.getText());
            user.setUserPassword(encryptedPassword);

            try {

                if (usersService.login(user)) {

                    this.dispose();

                    Menu formMenu = new Menu(this, user);
                    formMenu.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(this, "Datos incorrectos.");
                }

            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar los datos solicitados.");
        }

    }//GEN-LAST:event_buttonLoginActionPerformed

    private void textFieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldUserActionPerformed
        textFieldUser.transferFocus();
    }//GEN-LAST:event_textFieldUserActionPerformed

    /**
     * Al presionar el botón salir cierra el programa.
     *
     * @param evt
     */
    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    /**
     * Coloca al JFrame en una ubicación de acuerdo a la pocision de las
     * variables globales, y a la posicion obtenida al momento de realizar la
     * acción.
     *
     * @param evt
     */
    private void panelBackgroundBelowMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBackgroundBelowMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelBackgroundBelowMouseDragged

    /**
     * Toma la pocisión X, Y al estar presionando el mouse, y los asigna e las
     * variables globales.
     *
     * @param evt
     */
    private void panelBackgroundBelowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBackgroundBelowMousePressed

        x = evt.getX();
        y = evt.getY();

    }//GEN-LAST:event_panelBackgroundBelowMousePressed
    //  ------------------------------------------------------------------------

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

            UIManager.setLookAndFeel(new FlatIntelliJLaf());

        } catch (UnsupportedLookAndFeelException ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel labelGreeting;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel labelUserIcon;
    private javax.swing.JPanel panelBackgroundAbove;
    private javax.swing.JPanel panelBackgroundBelow;
    private javax.swing.JPasswordField passwordFieldPassword;
    private javax.swing.JTextField textFieldUser;
    // End of variables declaration//GEN-END:variables
}
