/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import Models.User;
import static Services.ChartService.generateGraphDonutNationalityPatients;
import static Services.ChartService.generateGraphDonutStatusPatients;
import Services.PatientsService;
import Utilities.WindowsBackground.CustomPanel;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.EmptyBorder;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtils;
import org.jfree.chart.JFreeChart;

/**
 *
 * @author JD101
 */
public class Statistics extends javax.swing.JFrame {

    //  Variables and Objects
    //  ------------------------------------------------------------------------
    private User user;
    private JFreeChart chartStatusPatients;
    private JFreeChart chartNationalityPatients;
    //  ------------------------------------------------------------------------

    /**
     * Creates new form Statistics
     *
     * @throws java.sql.SQLException
     */
    public Statistics() throws SQLException {

        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Images/Logo/logo.png")).getImage());
        initCharts();
        setTextLabels();
        setLocationRelativeTo(null);

    }

    /**
     * Crea un nuevo formulario Statistics.
     *
     * @param window Recibe un parámetro tipo JFrame para localizarse de acuerdo
     * a este.
     * @param user Recibe un parámetro de tipo User para mantener un control de
     * los permisos de usuario.
     * @throws SQLException
     */
    public Statistics(JFrame window, User user) throws SQLException {

        this.user = user;

        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Images/Logo/logo.png")).getImage());
        initCharts();
        setTextLabels();
        setLocationRelativeTo(window);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackgroundBelow = new CustomPanel("/Images/Statistics/backgroundBelow.png");
        panelBackgroundAbove = new CustomPanel("/Images/Statistics/background.png");
        panelChartNationality = new javax.swing.JPanel();
        panelChartTestStatus = new javax.swing.JPanel();
        panelTestStatusInfoImage = new CustomPanel("/Images/Statistics/TestStatusInfo.png");
        labelTestStatusInfo = new javax.swing.JLabel();
        buttonSaveTestStatusInfo = new javax.swing.JButton();
        panelNationalForeignImage = new CustomPanel("/Images/Statistics/NationalityInfo.png");
        labelNationalForeignInfo = new javax.swing.JLabel();
        buttonSaveNationalForeignInfo = new javax.swing.JButton();
        buttonRefresh = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estadísticas COVID-19");
        setResizable(false);

        panelBackgroundBelow.setPreferredSize(new java.awt.Dimension(900, 600));

        panelBackgroundAbove.setPreferredSize(new java.awt.Dimension(850, 550));

        panelChartNationality.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelChartNationality.setPreferredSize(new java.awt.Dimension(350, 250));

        javax.swing.GroupLayout panelChartNationalityLayout = new javax.swing.GroupLayout(panelChartNationality);
        panelChartNationality.setLayout(panelChartNationalityLayout);
        panelChartNationalityLayout.setHorizontalGroup(
            panelChartNationalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
        panelChartNationalityLayout.setVerticalGroup(
            panelChartNationalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        panelChartTestStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelChartTestStatus.setPreferredSize(new java.awt.Dimension(350, 250));

        javax.swing.GroupLayout panelChartTestStatusLayout = new javax.swing.GroupLayout(panelChartTestStatus);
        panelChartTestStatus.setLayout(panelChartTestStatusLayout);
        panelChartTestStatusLayout.setHorizontalGroup(
            panelChartTestStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
        panelChartTestStatusLayout.setVerticalGroup(
            panelChartTestStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        panelTestStatusInfoImage.setPreferredSize(new java.awt.Dimension(350, 150));

        labelTestStatusInfo.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        labelTestStatusInfo.setForeground(new java.awt.Color(255, 255, 255));
        labelTestStatusInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTestStatusInfo.setToolTipText("Resumen del estado de las pruebas.");
        labelTestStatusInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelTestStatusInfo.setName(""); // NOI18N
        labelTestStatusInfo.setPreferredSize(new java.awt.Dimension(210, 140));

        buttonSaveTestStatusInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Statistics/Save.png"))); // NOI18N
        buttonSaveTestStatusInfo.setBorder(null);
        buttonSaveTestStatusInfo.setMinimumSize(new java.awt.Dimension(0, 0));
        buttonSaveTestStatusInfo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Statistics/SaveRollOver.png"))); // NOI18N
        buttonSaveTestStatusInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveTestStatusInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTestStatusInfoImageLayout = new javax.swing.GroupLayout(panelTestStatusInfoImage);
        panelTestStatusInfoImage.setLayout(panelTestStatusInfoImageLayout);
        panelTestStatusInfoImageLayout.setHorizontalGroup(
            panelTestStatusInfoImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTestStatusInfoImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTestStatusInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(buttonSaveTestStatusInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelTestStatusInfoImageLayout.setVerticalGroup(
            panelTestStatusInfoImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTestStatusInfoImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTestStatusInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTestStatusInfoImageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSaveTestStatusInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        panelNationalForeignImage.setPreferredSize(new java.awt.Dimension(350, 150));

        labelNationalForeignInfo.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        labelNationalForeignInfo.setForeground(new java.awt.Color(255, 255, 255));
        labelNationalForeignInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNationalForeignInfo.setToolTipText("Personas nacionales y extranjeras.");
        labelNationalForeignInfo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelNationalForeignInfo.setPreferredSize(new java.awt.Dimension(230, 140));

        buttonSaveNationalForeignInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Statistics/Save.png"))); // NOI18N
        buttonSaveNationalForeignInfo.setBorder(null);
        buttonSaveNationalForeignInfo.setMinimumSize(new java.awt.Dimension(0, 0));
        buttonSaveNationalForeignInfo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Statistics/SaveRollOver.png"))); // NOI18N
        buttonSaveNationalForeignInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveNationalForeignInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNationalForeignImageLayout = new javax.swing.GroupLayout(panelNationalForeignImage);
        panelNationalForeignImage.setLayout(panelNationalForeignImageLayout);
        panelNationalForeignImageLayout.setHorizontalGroup(
            panelNationalForeignImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNationalForeignImageLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(buttonSaveNationalForeignInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(labelNationalForeignInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelNationalForeignImageLayout.setVerticalGroup(
            panelNationalForeignImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNationalForeignImageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNationalForeignInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelNationalForeignImageLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(buttonSaveNationalForeignInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Statistics/Refresh.png"))); // NOI18N
        buttonRefresh.setBorder(null);
        buttonRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonRefresh.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Statistics/RefreshRollOver.png"))); // NOI18N
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Statistics/Exit.png"))); // NOI18N
        jButton2.setText("Atrás");
        jButton2.setBorder(null);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Statistics/ExitRollOver.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBackgroundAboveLayout = new javax.swing.GroupLayout(panelBackgroundAbove);
        panelBackgroundAbove.setLayout(panelBackgroundAboveLayout);
        panelBackgroundAboveLayout.setHorizontalGroup(
            panelBackgroundAboveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundAboveLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(panelNationalForeignImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelChartNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(panelBackgroundAboveLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelChartTestStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTestStatusInfoImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelBackgroundAboveLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(buttonRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(75, 75, 75))
        );
        panelBackgroundAboveLayout.setVerticalGroup(
            panelBackgroundAboveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundAboveLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelBackgroundAboveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBackgroundAboveLayout.createSequentialGroup()
                        .addComponent(panelChartTestStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelNationalForeignImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBackgroundAboveLayout.createSequentialGroup()
                        .addComponent(panelTestStatusInfoImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(panelChartNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(panelBackgroundAboveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonRefresh, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout panelBackgroundBelowLayout = new javax.swing.GroupLayout(panelBackgroundBelow);
        panelBackgroundBelow.setLayout(panelBackgroundBelowLayout);
        panelBackgroundBelowLayout.setHorizontalGroup(
            panelBackgroundBelowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundBelowLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelBackgroundAbove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        panelBackgroundBelowLayout.setVerticalGroup(
            panelBackgroundBelowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundBelowLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelBackgroundAbove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(panelBackgroundBelow, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //  Own Code
    //  ------------------------------------------------------------------------
    /**
     * Genera un objeto de tipo ChartPanel con medidas específicas.
     *
     * @param chart Recibe un objeto de tipo JFreeChart para generar el objeto
     * ChartPanel.
     * @return Retorna un objeto de tipo ChartPanel generado con el parametro
     * recibido.
     */
    private ChartPanel generateChartPanel(JFreeChart chart) {

        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setSize(350, 250);

        return chartPanel;

    }

    /**
     * Inicializa los gráficos globales y los ñade al panel respectivo de cada
     * uno.
     *
     * @throws SQLException
     */
    private void initCharts() throws SQLException {

        this.chartStatusPatients = generateGraphDonutStatusPatients();
        this.chartNationalityPatients = generateGraphDonutNationalityPatients();

        panelChartTestStatus.add(generateChartPanel(this.chartStatusPatients));
        panelChartNationality.add(generateChartPanel(this.chartNationalityPatients));

    }

    /**
     * Inicializa los textos que van a mostrar el reporte de la cantidad de
     * estados de las pruebas, las personas nacionales y extranjeras.
     *
     * @throws SQLException
     */
    public void setTextLabels() throws SQLException {

        PatientsService patientsService = new PatientsService();

        String totalPatients = patientsService.getTotalPatients();
        ArrayList<String> listResultsStates = patientsService.getTotalPatientsAllStatus();
        ArrayList<Integer> listResultsNationalForeign = patientsService.getTotalNationalForeign();

        labelTestStatusInfo.setText("<html><strong>Total de personas: " + totalPatients + "</strong><br><br>"
                + "Total de pruebas negativas: " + listResultsStates.get(0) + "<br>"
                + "Total de pruebas pendientes: " + listResultsStates.get(1) + "<br>"
                + "Total de pruebas positivas: " + listResultsStates.get(2) + "<br>"
                + "Total de recuperados: " + listResultsStates.get(3) + "</html>");
        labelTestStatusInfo.setBorder(new EmptyBorder(0, 15, 0, 0));

        labelNationalForeignInfo.setText("<html>Personas Nacionales: " + listResultsNationalForeign.get(0) + "<br><br>"
                + "Personas Extranjeras: " + listResultsNationalForeign.get(1) + "</html>");
        labelNationalForeignInfo.setBorder(new EmptyBorder(0, 0, 0, 15));

    }

    /**
     * Guarda el gráfico del estado de las pruebas como una imagen en formato
     * .png
     *
     * @param evt
     */
    private void buttonSaveTestStatusInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveTestStatusInfoActionPerformed

        try {
            ChartUtils.saveChartAsPNG(new File("reports/Charts/PeopleStatusChart.png"), this.chartStatusPatients, 600, 500);
        } catch (IOException ex) {
            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buttonSaveTestStatusInfoActionPerformed

    /**
     * Guarda el gráfico de la cantidad de personas nacionales y extranjeros
     * como una imagen en formato .png
     *
     * @param evt
     */
    private void buttonSaveNationalForeignInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveNationalForeignInfoActionPerformed

        try {
            ChartUtils.saveChartAsPNG(new File("reports/Charts/NationalForeignChart.png"), this.chartNationalityPatients, 600, 500);
        } catch (IOException ex) {
            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buttonSaveNationalForeignInfoActionPerformed

    /**
     * Refresca los gráficos y el texto de los reportes.
     *
     * @param evt
     */
    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed

        try {

            initCharts();
            setTextLabels();

        } catch (SQLException ex) {
            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buttonRefreshActionPerformed

    /**
     * Cierra este formulario e instancia uno nuevo de tipo Menu, y lo hace
     * visible.
     *
     * @param evt
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.dispose();

        Menu formMenu = new Menu(this, this.user);
        formMenu.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed
    //  ------------------------------------------------------------------------

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

            UIManager.setLookAndFeel(new FlatIntelliJLaf());

        } catch (UnsupportedLookAndFeelException ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Statistics().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JButton buttonSaveNationalForeignInfo;
    private javax.swing.JButton buttonSaveTestStatusInfo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel labelNationalForeignInfo;
    private javax.swing.JLabel labelTestStatusInfo;
    private javax.swing.JPanel panelBackgroundAbove;
    private javax.swing.JPanel panelBackgroundBelow;
    private javax.swing.JPanel panelChartNationality;
    private javax.swing.JPanel panelChartTestStatus;
    private javax.swing.JPanel panelNationalForeignImage;
    private javax.swing.JPanel panelTestStatusInfoImage;
    // End of variables declaration//GEN-END:variables
}
